"""
SEMANTIC TRANSFORMS — move a Layer Design's ARCHITECTURE, then resolve it.

The Layer Assembly owns transform-group choices (which walls follow which
centre, per layer). It asks the Designer (LayerSource.geometry(design,
transforms)) for the design resolved with those groups applied — instead of
moving already-resolved beads. Here the transforms are applied to the SOURCE
PATHS of the design's document; the normal Designer pipeline then builds
walls, junctions, openings, lattice and printable geometry from the result.

    transforms: {source path id: (k, tx, ty)}  p' = k·p + (tx, ty)
                (design coordinates; a uniform scale + translation — the
                Assembly's group placement relative to the layer's own)

RULES (V1):
  * A closed source (rectangle, circle, ellipse, closed polyline) and an
    open source with no attached end take its OWN transform (identity if
    unlisted). Sizes scale; wall thickness, offsets, Corner R and opening
    WIDTHS are physical and do not.
  * ATTACHMENTS are derived from the UNTRANSFORMED design (the relation the
    Designer's wall network forms by coincidence: an open end lying on /
    inside another source's wall — network.find_attachments), never by a
    per-layer nearest-point search on transformed geometry. Each attached
    end is stored as (host, foot on the host centre line, offset from it);
    its image is host_map(foot) + offset, so the end stays ON its
    transformed host (the offset is physical).
  * An open source whose two ends map differently is a CONNECTOR between
    transformed hosts: it is REGENERATED by the similarity fixing its two
    end images (a straight line stays a straight line between the new
    attachment points; a curve keeps its shape, rotated / scaled). Its own
    group (if any) applies only to an end that is not attached. Wall
    thickness, alignment, source id, network membership and infill stay;
    the Designer then builds its faces, ordinary junctions (miter / rounded
    as configured) and lattice — nothing is stretched.
  * HUBS (open ends meeting each other, not on a host body) move with the
    own transform of the member with the smallest source id.
  * Openings keep their width; their position along a scaled host scales
    with it (center_s · k). Region overrides likewise.
  * Inset paths are re-derived from their (transformed) parent by the
    Designer; their frozen points follow the parent's map.
DERIVED JUNCTION vs EXPLICIT CONNECTOR (relations()): forms that merely
INTERSECT have a derived junction — the Designer recomputes it from the
transformed forms; it shrinks and disappears when they separate (no bridge
is invented; report 'junctions' [{sources, present}]). An authored open wall
attached to forms is a connector — regenerated between its transformed
attachments (report 'connectors'). Effective walls (network inheritance,
the single-bead override) follow the Designer's rule: effective_walls().
LIMITATION: there are no persistent attachment constraints yet — the
relation is whatever coincidence the untransformed design has (snapping),
re-derived per design (not per layer). An end that merely LOOKS attached
(near, not on / inside a wall) is free.
"""
from __future__ import annotations

import copy
import json
import math

OPEN_TYPES = ('LinePath', 'QuadBezierPath', 'ExplicitPath')
ID = (1.0, 0.0, 0.0)


def _is_identity(t, eps=1e-9):
    return abs(t[0] - 1) <= eps and abs(t[1]) <= 1e-7 and abs(t[2]) <= 1e-7


def _apply(t, p):
    return (t[0] * p[0] + t[1], t[0] * p[1] + t[2])


def _ends(d):
    t = d.get('type', 'ExplicitPath')
    if t in ('LinePath', 'QuadBezierPath'):
        return tuple(d['start']), tuple(d['end'])
    pts = d.get('control_points', d.get('points')) or []
    return (tuple(pts[0]), tuple(pts[-1])) if len(pts) >= 2 else None


def _is_open(d):
    return d.get('type', 'ExplicitPath') in OPEN_TYPES and not d.get('closed')


_WALLS: dict = {}


def effective_walls(doc) -> dict:
    """{source id: (thickness, align, kind)} — each source's EFFECTIVE wall,
    the Designer's rule (model.PrintLayer._wall_offsets): its own wall, else
    the Network Wall of the SOURCE NETWORK it belongs to (sources whose
    centre lines touch / cross, transitively — network.find_contacts), else
    none. kind: 'wall' (thickness > 0); 'single' (a single bead — no wall, or
    the explicit Wall Thickness 0 override inside a thick-walled network);
    'lanes' (a single-bead path that physical rules print as two return
    lanes: open, or a closed one opened by an opening)."""
    key = json.dumps([doc.get('source_paths'), doc.get('network_walls'), doc.get('openings'),
                      doc.get('infills'), doc.get('material')], sort_keys=True)
    hit = _WALLS.get(key)
    if hit is not None:
        return hit
    import network as N
    from model import Vec2
    srcs = [d for d in doc.get('source_paths') or [] if d.get('id')]
    lines = {d['id']: _centreline(d) for d in srcs
             if not (d.get('type') == 'InsetPath' and not d.get('points'))}
    beads = [N.Bead(sid, [Vec2(*q) for q in pts], False, N.WIRE, f'S:{sid}')
             for sid, pts in lines.items() if len(pts) >= 2]
    uf = N.UnionFind()
    for b in beads:
        uf.find(b.element)
    for a, b in N.find_contacts(beads):
        uf.union(a, b)
    nws = doc.get('network_walls') or []
    mat = doc.get('material') or {}
    physical = bool(mat.get('physical'))
    opened = {o.get('source_path_id') for o in doc.get('openings') or []} - \
        {f.get('path_id') for f in doc.get('infills') or []}
    extra = {o.get('source_path_id') for o in doc.get('offset_treatments') or []}
    out = {}
    for d in srcs:
        sid = d['id']
        w = d.get('wall')
        if isinstance(w, dict) and 'thickness' in w:
            t, align = max(0.0, float(w.get('thickness') or 0)), w.get('align') or 'auto'
        else:
            nw = next((x for x in nws if x.get('path_id') in lines and sid in lines
                       and uf.find(f"S:{x['path_id']}") == uf.find(f'S:{sid}')), None)
            t, align = (float(nw.get('thickness') or 0), nw.get('align') or 'auto') if nw else (0.0, 'auto')
        if t > 1e-9:
            kind = 'wall'
        elif physical and (_is_open(d) or sid in opened) and sid not in extra:
            kind = 'lanes'
        else:
            kind = 'single'
        out[sid] = (t if kind == 'wall' else 0.0, align, kind)
    if len(_WALLS) > 64:
        _WALLS.clear()
    _WALLS[key] = out
    return out


def _thickness(doc, d):
    """A source's effective WALL thickness (0: a single-bead path)."""
    return effective_walls(doc).get(d.get('id'), (0.0, 'auto', 'single'))[0]


def _centreline(d):
    """Dense centre line of a source record (Designer sampling)."""
    from app import _deserialise_path
    p = _deserialise_path(d)
    t = d.get('type', 'ExplicitPath')
    n = 4096 if t in ('CirclePath', 'EllipsePath', 'QuadBezierPath') else 64
    try:
        pts = [(q.x, q.y) for q in p.sample_points(n)]
    except TypeError:
        pts = [(q.x, q.y) for q in p.sample_points()]
    if p.closed and len(pts) > 2 and pts[0] != pts[-1]:
        pts.append(pts[0])
    return pts


def _foot(e, pts):
    best = (math.inf, None)
    for a, b in zip(pts, pts[1:]):
        dx, dy = b[0] - a[0], b[1] - a[1]
        L2 = dx * dx + dy * dy
        t = 0.0 if L2 == 0 else max(0.0, min(1.0, ((e[0] - a[0]) * dx + (e[1] - a[1]) * dy) / L2))
        q = (a[0] + t * dx, a[1] + t * dy)
        dd = math.dist(e, q)
        if dd < best[0]:
            best = (dd, q)
    return best


def attachments(doc) -> dict:
    """{(source id, end 0|1): ('T', host id, foot, offset) | ('hub', anchor id)}
    from the UNTRANSFORMED document (see module doc)."""
    srcs = [d for d in doc.get('source_paths') or [] if d.get('id')]
    lines = {}
    out = {}
    for d in srcs:
        if not _is_open(d) or _ends(d) is None:
            continue
        for w, e in enumerate(_ends(d)):
            # another open source's END at the same point → hub (the network's rule)
            hub = [q['id'] for q in srcs if q is not d and _is_open(q) and _ends(q)
                   and any(math.dist(e, x) <= 1e-6 for x in _ends(q))]
            if hub:
                out[(d['id'], w)] = ('hub', min([d['id']] + hub))
                continue
            best = None
            for q in srcs:
                if q is d or q.get('type') == 'InsetPath' and not q.get('points'):
                    continue
                if q['id'] not in lines:
                    lines[q['id']] = _centreline(q)
                dist, foot = _foot(e, lines[q['id']])
                band = max(1e-6, _thickness(doc, q))         # on its centre line, or inside its wall
                if foot is not None and dist <= band and (best is None or dist < best[0]):
                    best = (dist, q['id'], foot)
            if best is not None:
                _, hid, foot = best
                out[(d['id'], w)] = ('T', hid, foot, (e[0] - foot[0], e[1] - foot[1]))
    return out


def _similarity(e0, e1, f0, f1):
    """z' = a z + b with e0 → f0, e1 → f1 (complex arithmetic)."""
    z0, z1, w0, w1 = complex(*e0), complex(*e1), complex(*f0), complex(*f1)
    if abs(z1 - z0) < 1e-12:
        return None
    a = (w1 - w0) / (z1 - z0)
    b = w0 - a * z0
    return a, b


def _map_point(m, p):
    if m[0] == 'sim':
        k, tx, ty = m[1]
        return (k * p[0] + tx, k * p[1] + ty)
    a, b = m[1]
    z = a * complex(*p) + b
    return (z.real, z.imag)


def _scale_of(m):
    return m[1][0] if m[0] == 'sim' else abs(m[1][0])


def _transform_record(d, m):
    """The source record moved by map m (geometry only; walls stay)."""
    d = copy.deepcopy(d)
    t = d.get('type', 'ExplicitPath')
    k = _scale_of(m)
    P = lambda p: list(_map_point(m, p))
    if t == 'LinePath':
        d['start'], d['end'] = P(d['start']), P(d['end'])
    elif t == 'QuadBezierPath':
        d['start'], d['end'], d['control'] = P(d['start']), P(d['end']), P(d['control'])
    elif t == 'CirclePath':
        d['cx'], d['cy'] = P((d['cx'], d['cy']))
        d['radius'] = d['radius'] * k
    elif t == 'EllipsePath':
        d['cx'], d['cy'] = P((d['cx'], d['cy']))
        d['rx'], d['ry'] = d['rx'] * k, d['ry'] * k
    elif t == 'RectanglePath':
        d['x'], d['y'] = P((d['x'], d['y']))
        d['w'], d['h'] = d['w'] * k, d['h'] * k
    else:                                            # ExplicitPath, InsetPath (frozen points)
        for key in ('control_points', 'points'):
            if d.get(key):
                d[key] = [P(p) for p in d[key]]
    return d


def source_maps(doc, transforms, atts=None) -> dict:
    """{source id: map} as transform_document applies them (identity
    omitted) — for carrying wall-relative data (lattice stations) along."""
    return transform_document(doc, transforms, atts, _maps_only=True)


def map_wall_point(maps, lines, owner, p):
    """A point of the untransformed design carried WALL-RELATIVELY: its foot
    on the owning source's centre line goes through that source's map, its
    offset from it stays physical (rotated with a regenerated connector)."""
    sid = owner(p)
    m = maps.get(sid)
    if m is None or sid not in lines:
        return p
    _, foot = _foot(p, lines[sid])
    f = _map_point(m, foot)
    off = (p[0] - foot[0], p[1] - foot[1])
    if m[0] == 'cplx':
        a = m[1][0]
        u = a / abs(a) if abs(a) > 1e-12 else 1
        z = u * complex(*off)
        off = (z.real, z.imag)
    return (f[0] + off[0], f[1] + off[1])


def transform_document(doc, transforms, atts=None, _maps_only=False) -> tuple:
    """(transformed document, report). transforms: {source id: (k, tx, ty)}.
    atts: attachments(doc) (pass it when transforming the same design for
    many layers)."""
    transforms = {s: tuple(t) for s, t in (transforms or {}).items() if not _is_identity(tuple(t))}
    if not transforms:
        return {} if _maps_only else (doc, {'connectors': [], 'moved': []})
    if atts is None:
        atts = attachments(doc)
    srcs = {d['id']: d for d in doc.get('source_paths') or [] if d.get('id')}
    maps = {}

    def own(sid):
        return ('sim', transforms.get(sid, ID))

    # closed / free sources first; then open sources whose ends are attached
    # (hosts first — a host that is itself a connector is resolved before
    # the sources attached to it; a cycle falls back to the own transform)
    for sid, d in srcs.items():
        if not _is_open(d):
            maps[sid] = own(sid)
    pending = [sid for sid in srcs if sid not in maps]
    connectors = []
    for _ in range(len(pending) + 1):
        if not pending:
            break
        rest = []
        for sid in pending:
            d = srcs[sid]
            ends = _ends(d)
            if ends is None:
                maps[sid] = own(sid)
                continue
            imgs, hosts, ready = [], [], True
            for w, e in enumerate(ends):
                a = atts.get((sid, w))
                if a is None:
                    imgs.append(_map_point(own(sid), e)); hosts.append(None)
                elif a[0] == 'hub':
                    imgs.append(_map_point(own(a[1]), e)); hosts.append(None)
                else:
                    _, hid, foot, off = a
                    if hid not in maps:
                        ready = False
                        break
                    f = _map_point(maps[hid], foot)
                    imgs.append((f[0] + off[0], f[1] + off[1])); hosts.append(hid)
            if not ready:
                rest.append(sid)
                continue
            mine = [_map_point(own(sid), e) for e in ends]
            if all(math.dist(a, b) < 1e-9 for a, b in zip(imgs, mine)):
                maps[sid] = own(sid)
                continue
            sim = _similarity(ends[0], ends[1], imgs[0], imgs[1])
            maps[sid] = ('cplx', sim) if sim else own(sid)
            if sim:
                connectors.append({'source': sid, 'hosts': hosts, 'scale': abs(sim[0]),
                                   'ends': [list(p) for p in imgs]})
        if len(rest) == len(pending):                # attachment cycle
            for sid in rest:
                maps[sid] = own(sid)
            rest = []
        pending = rest
    if _maps_only:
        return {k: m for k, m in maps.items() if not (m[0] == 'sim' and _is_identity(m[1]))}

    out = copy.deepcopy(doc)
    moved = []
    new_src = []
    for d in out.get('source_paths') or []:
        m = maps.get(d.get('id'))
        if d.get('type') == 'InsetPath':
            m = maps.get(d.get('parent_id'), m)
        if m is None or (m[0] == 'sim' and _is_identity(m[1])):
            new_src.append(d)
            continue
        new_src.append(_transform_record(d, m))
        moved.append(d['id'])
    out['source_paths'] = new_src
    for o in out.get('openings') or []:                 # width physical; position scales
        m = maps.get(o.get('source_path_id'))
        if m is not None:
            o['center_s'] = float(o.get('center_s', 0.0)) * _scale_of(m)
    for r in out.get('region_overrides') or []:
        m = maps.get(r.get('path_id'))
        if m is not None:
            r['s'] = float(r.get('s', 0.0)) * _scale_of(m)
    return out, {'connectors': connectors, 'moved': sorted(moved),
                 'junctions': derived_junctions(doc, out)}


def _contacts(doc) -> set:
    """{frozenset((a, b))}: sources whose centre lines touch / cross."""
    import network as N
    from model import Vec2
    beads = []
    for d in doc.get('source_paths') or []:
        if not d.get('id') or (d.get('type') == 'InsetPath' and not d.get('points')):
            continue
        pts = _centreline(d)
        if len(pts) >= 2:
            beads.append(N.Bead(d['id'], [Vec2(*q) for q in pts], False, N.WIRE, f"S:{d['id']}"))
    return {frozenset((a[2:], b[2:])) for a, b in N.find_contacts(beads) if a != b}


_RELATIONS: dict = {}


def relations(doc, atts=None) -> dict:
    """The two kinds of architectural relationship a semantic transform
    distinguishes (from the UNTRANSFORMED design):
      connectors — EXPLICIT: an open source (an authored wall) whose end(s)
        are attached to other forms. It stays a wall as its hosts move:
        regenerated between the transformed attachments ({source, path:
        'straight' | 'curve', attachments: [{end, host, foot, offset}]} —
        the path kind is kept, so curved / routed strategies can follow).
      derived — forms that merely INTERSECT (touching / crossing centre
        lines, no attachment between them): their junction is DERIVED
        geometry, recomputed by the Designer from the transformed forms; it
        shrinks and disappears when they separate (no bridge is invented)."""
    key = json.dumps([doc.get('source_paths'), doc.get('network_walls'), doc.get('material')],
                     sort_keys=True)                                 # per DESIGN, not per layer
    hit = _RELATIONS.get(key)
    if hit is not None:
        return hit
    atts = attachments(doc) if atts is None else atts
    srcs = {d['id']: d for d in doc.get('source_paths') or [] if d.get('id')}
    conns, attached = [], set()
    for sid, d in srcs.items():
        ends = [(w, atts.get((sid, w))) for w in (0, 1)]
        tees = [(w, a) for w, a in ends if a and a[0] == 'T']
        if not _is_open(d) or not tees:
            continue
        conns.append({'source': sid, 'path': 'straight' if d.get('type') == 'LinePath' else 'curve',
                      'attachments': [{'end': w, 'host': a[1], 'foot': list(a[2]), 'offset': list(a[3])}
                                      for w, a in tees]})
        attached |= {frozenset((sid, a[1])) for _, a in tees}
    derived = sorted(sorted(p) for p in _contacts(doc) - attached)
    if len(_RELATIONS) > 64:
        _RELATIONS.clear()
    _RELATIONS[key] = out = {'connectors': conns, 'derived': derived}
    return out


def derived_junctions(doc, tdoc) -> list:
    """[{sources: [a, b], present}] — each DERIVED junction of the
    untransformed design and whether the transformed forms still intersect
    (False: the junction has disappeared; the forms are separate there)."""
    rel = relations(doc)
    now = _contacts(tdoc) if tdoc is not doc else None
    return [{'sources': p, 'present': True if now is None else frozenset(p) in now}
            for p in rel['derived']]


def spec_key(transforms) -> str:
    """A stable key for a transforms spec (rounded)."""
    items = sorted((s, round(t[0], 12), round(t[1], 9), round(t[2], 9))
                   for s, t in (transforms or {}).items() if not _is_identity(tuple(t)))
    return json.dumps(items)
